export const APP_SHELL_COPY = {
  avatarFallback: "?",
  brand: "Ledgerly",
  linkAccounts: "Accounts",
  linkAnnuities: "Annuities",
  linkGoals: "Goals",
  linkInvest: "Invest",
  linkInvestments: "Investments",
  linkLedgers: "Ledgers",
  linkProfile: "Profile",
  linkReconcile: "Reconcile",
  linkReports: "Reports",
  menuButtonLabel: "Open navigation menu",
  mobileNavLabel: "Mobile navigation",
  moreLabel: "More",
  moreOverflowTitle: "More destinations",
  userMenuLabel: "Open user menu",
} as const;
