export const USER_PROFILE_COPY = {
  changeEmailButton: "Update Email",
  changeEmailLabel: "New Email Address",
  changePasswordButton: "Update Password",
  changePasswordCurrentLabel: "Current Password",
  changePasswordNewLabel: "New Password",
  displayNameButton: "Update Name",
  displayNameLabel: "Display Name",
  emailSectionTitle: "Email Address",
  genericError: "An unexpected error occurred. Please try again.",
  passwordSectionTitle: "Change Password",
  profileSectionTitle: "Profile",
  signOutButton: "Sign Out",
  title: "Account Settings",
} as const;
