export const RECONCILE_VIEW_COPY = {
  actionApply: "Apply",
  actionConfirmed: "Confirmed",
  actionProjected: "Projected",
  cashFlowAccountBalancesLabel: "Account balances",
  cashFlowRecommendedActionsLabel: "Recommended actions",
  cashFlowSectionLabel: "CASH FLOW",
  inputsNeededHeading: "Inputs needed",
  inputsTableAccountHeader: "Account",
  inputsTableBalanceHeader: "Balance",
  inputsTableStatusHeader: "Status",
  inputsTableStatusConfirmed: "✓ confirmed",
  inputsTableStatusPending: "pending",
  investmentExplanationHeading: "Why this investment amount?",
  pageHeading: "Reconcile",
  tagline: "Where the money is, and where it should go.",
  tileAssignToLedgers: "To assign to ledgers",
  tileCashSurplus: "Cash surplus",
  tileInterTierTransfer: "Inter-tier transfer",
  tileToInvest: "To invest",
} as const;
