export const SIGN_UP_FORM_COPY = {
  title: "Create an account",
  description: "Enter your details to create a new account.",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "••••••••",
  confirmPasswordLabel: "Confirm password",
  confirmPasswordPlaceholder: "••••••••",
  submitButton: "Create account",
  loadingButton: "Creating account…",
  signInPrompt: "Already have an account?",
  signInLink: "Sign in",
  errorEmailRequired: "Email is required.",
  errorEmailInvalid: "Please enter a valid email address.",
  errorPasswordRequired: "Password is required.",
  errorPasswordTooShort: "Password must be at least 8 characters.",
  errorConfirmPasswordRequired: "Please confirm your password.",
  errorPasswordMismatch: "Passwords do not match.",
} as const;
