export const SIGN_UP_FORM_COPY = {
  title: "Create an account",
  description: "Enter your details to create a new account.",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "••••••••",
  confirmPasswordLabel: "Confirm password",
  confirmPasswordPlaceholder: "••••••••",
  submitButton: "Create account",
  loadingButton: "Creating account…",
  signInPrompt: "Already have an account?",
  signInLink: "Sign in",
  errorEmailRequired: "Email is required.",
  errorEmailInvalid: "Please enter a valid email address.",
  errorPasswordRequired: "Password is required.",
  errorPasswordTooShort: "Password must be at least 8 characters.",
  errorConfirmPasswordRequired: "Please confirm your password.",
  errorPasswordMismatch: "Passwords do not match.",
  errorEmailAlreadyInUse: "An account with this email address already exists.",
  errorInvalidEmail: "The email address is not valid.",
  errorWeakPassword: "Password is too weak. Please choose a stronger password.",
  errorOperationNotAllowed:
    "Email/password sign-up is not enabled. Please contact support.",
  errorDefault: "An unexpected error occurred. Please try again.",
} as const;
